name: chicago-neighborhood-premium
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - matplotlib
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - joblib
  - scipy
  - geopandas
  - optuna
  - missingno
